### ISSUE TITLE
Over resource limit on Streamlit Cloud

### ISSUE THREAD

**Issue by ghost** [londoncyclingcampaign/lcc-dangerous-junctions#50]
Hello, your app has gone over its resource limit. (Evidently popular and for good reason!) It suggested a message to put here, but it seemed a little patronising imo so I'm just writing this. Cheers

**Comment by danielhills** [comment]
Yes, we're seeing issues today due to high volumes of traffic, apologies. That message is from streamlit - we're hoping they will be able to increase resources to improve performance.

**Comment by danielhills** [comment]
Issue logged on streamlit here - https://discuss.streamlit.io/t/over-resource-limit-issues/54982

**Comment by danielhills** [comment]
Okay, the app now has double the previous resources and appears to be loading and updating quicker. Some of this is likely due to a drop off in users though.

I will close this issue for now, but add a new one for some longer term improvements I plan to make in the future - fix any memory leaks, potentially self host etc.
